"""End-to-end registration test against a live Postgres + the FastAPI app.

The fixture seeds an `application_pepper` row, then each test uses
the AsyncClient to POST /auth/register, asserts the response, and
cleans up the rows it created. Tests run sequentially against the
shared dev DB; isolation is by per-test email so two parallel runs
of the same email would collide — fine for now.
"""

from __future__ import annotations

import base64
import hashlib
import json
import secrets
import uuid
from collections.abc import AsyncIterator

import jwt
import pytest
from httpx import AsyncClient
from nacl.signing import SigningKey
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.pool import NullPool

from kinetica.config import get_settings
from kinetica.crypto import compute_email_hash
from kinetica.models import ApplicationPepper, User, UserDevice


def _b64(b: bytes) -> str:
    return base64.b64encode(b).decode("ascii")


def _build_payload(
    *,
    email: str = "user@example.com",
    device_name: str = "iPhone",
    device_signing_key: SigningKey | None = None,
) -> tuple[dict[str, str], SigningKey]:
    """Construct a valid registration payload deterministically.

    The byte fields are not cryptographically meaningful for the route's
    accept/reject contract — only the bootstrap_signature must verify
    against device_pubkey. We therefore pin random-but-fixed-shape values
    for everything else and fix the device keypair so the signature
    can be regenerated by the test.
    """
    sk = device_signing_key or SigningKey.generate()
    device_pubkey = sk.verify_key.encode()

    body_without_sig = {
        "email": email,
        "password_salt": _b64(secrets.token_bytes(16)),
        "encryption_pubkey": _b64(secrets.token_bytes(32)),
        "wrapped_master_key": _b64(secrets.token_bytes(72)),
        "device_pubkey": _b64(device_pubkey),
        "device_name": device_name,
    }
    canonical = json.dumps(body_without_sig, sort_keys=True, separators=(",", ":")).encode("utf-8")
    digest = hashlib.sha256(canonical).digest()
    signature = sk.sign(digest).signature

    return {**body_without_sig, "bootstrap_signature": _b64(signature)}, sk


@pytest.fixture
async def db_session() -> AsyncIterator[AsyncSession]:
    # NullPool: each session opens its own short-lived connection and
    # closes it on session exit. This avoids asyncpg background tasks
    # that try to create cancellation work on a loop that pytest has
    # already torn down between tests.
    engine = create_async_engine(
        get_settings().database_url,
        future=True,
        poolclass=NullPool,
    )
    sessionmaker = async_sessionmaker(engine, expire_on_commit=False)
    async with sessionmaker() as session:
        yield session


@pytest.fixture
async def primary_pepper(db_session: AsyncSession) -> AsyncIterator[bytes]:
    """Ensure exactly one 'primary' row exists for the duration of the test."""
    pepper = secrets.token_bytes(32)
    existing = (
        await db_session.execute(
            select(ApplicationPepper).where(ApplicationPepper.slot == "primary")
        )
    ).scalar_one_or_none()
    if existing is None:
        db_session.add(ApplicationPepper(slot="primary", pepper=pepper))
    else:
        existing.pepper = pepper
        pepper = pepper  # the test sees the new pepper
    await db_session.commit()
    yield pepper


@pytest.fixture
async def cleanup_users(db_session: AsyncSession) -> AsyncIterator[None]:
    """Track and delete users created during the test."""
    yield
    # Cascade through user_devices via FK ON DELETE CASCADE.
    await db_session.execute(delete(UserDevice))
    await db_session.execute(delete(User))
    await db_session.commit()


async def test_register_201_creates_user_and_device(
    client: AsyncClient,
    db_session: AsyncSession,
    primary_pepper: bytes,
    cleanup_users: None,
) -> None:
    payload, _sk = _build_payload(email="alice@example.com")
    response = await client.post("/auth/register", json=payload)
    assert response.status_code == 201, response.text

    body = response.json()
    user_id = uuid.UUID(body["user_id"])
    device_id = uuid.UUID(body["device_id"])
    assert body["token_type"] == "DPoP"
    assert body["access_token"]
    assert body["refresh_token"]

    # The DB row should carry an email_hash matching HMAC(pepper, email).
    user = (await db_session.execute(select(User).where(User.id == user_id))).scalar_one()
    assert user.email_hash == compute_email_hash("alice@example.com", primary_pepper)
    assert len(user.encryption_pubkey) == 32
    assert len(user.password_salt) == 16
    assert len(user.wrapped_master_key) >= 72
    # The route MUST NOT persist the email itself anywhere reachable.
    # users only carries email_hash; no plaintext column exists.

    device = (
        await db_session.execute(select(UserDevice).where(UserDevice.id == device_id))
    ).scalar_one()
    assert len(device.device_pubkey) == 32
    assert device.device_name == "iPhone"
    assert device.user_id == user_id
    assert device.bootstrap_pending is False
    assert device.revoked_at is None


async def test_access_token_carries_cnf_jwk_for_device_pubkey(
    client: AsyncClient,
    primary_pepper: bytes,
    cleanup_users: None,
) -> None:
    payload, sk = _build_payload(email="bob@example.com")
    response = await client.post("/auth/register", json=payload)
    assert response.status_code == 201
    token = response.json()["access_token"]

    settings = get_settings()
    decoded = jwt.decode(token, settings.jwt_secret, algorithms=["HS256"])
    assert decoded["sub"] == response.json()["user_id"]
    assert decoded["did"] == response.json()["device_id"]
    cnf_jwk = decoded["cnf"]["jwk"]
    assert cnf_jwk["kty"] == "OKP"
    assert cnf_jwk["crv"] == "Ed25519"
    # base64url-no-padding of the device pubkey.
    expected_x = base64.urlsafe_b64encode(sk.verify_key.encode()).rstrip(b"=").decode("ascii")
    assert cnf_jwk["x"] == expected_x


async def test_register_400_when_bootstrap_signature_fails(
    client: AsyncClient,
    primary_pepper: bytes,
    cleanup_users: None,
) -> None:
    payload, _sk = _build_payload(email="carol@example.com")
    # Replace signature with random 64 bytes — same shape, won't verify.
    payload["bootstrap_signature"] = _b64(secrets.token_bytes(64))
    response = await client.post("/auth/register", json=payload)
    assert response.status_code == 400
    assert "bootstrap_signature" in response.json()["detail"]


async def test_register_409_when_email_already_registered(
    client: AsyncClient,
    primary_pepper: bytes,
    cleanup_users: None,
) -> None:
    first, _sk1 = _build_payload(email="dup@example.com")
    second, _sk2 = _build_payload(email="dup@example.com")  # different keys
    r1 = await client.post("/auth/register", json=first)
    assert r1.status_code == 201
    r2 = await client.post("/auth/register", json=second)
    assert r2.status_code == 409


async def test_register_422_when_byte_lengths_violate_schema(
    client: AsyncClient,
    primary_pepper: bytes,
    cleanup_users: None,
) -> None:
    payload, _sk = _build_payload(email="eve@example.com")
    # 17-byte salt instead of 16.
    payload["password_salt"] = _b64(secrets.token_bytes(17))
    response = await client.post("/auth/register", json=payload)
    assert response.status_code == 422


async def test_register_503_when_pepper_table_empty(
    client: AsyncClient,
    db_session: AsyncSession,
    cleanup_users: None,
) -> None:
    # Wipe the primary pepper for this test; restore at teardown.
    await db_session.execute(delete(ApplicationPepper))
    await db_session.commit()
    try:
        payload, _sk = _build_payload(email="frank@example.com")
        response = await client.post("/auth/register", json=payload)
        assert response.status_code == 503
    finally:
        # Restore so subsequent tests in this file can rely on the fixture.
        db_session.add(ApplicationPepper(slot="primary", pepper=secrets.token_bytes(32)))
        await db_session.commit()
